name: Selenium Python Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'         # Ignore pushes that only change README.md
      - '*.md'              # Ignore pushes that only change other markdown files
      - '.github/**'        # Ignore pushes that only change workflow configs
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '.github/**'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager

      - name: Run tests
        run: |
          pytest selenium_tests/
